### ISSUE TITLE
Automatic health endpoint at /health

### ISSUE THREAD

**Issue by BurnedChris** [ardatan/feTS#205]
**Is your feature request related to a problem? Please describe.**
A default health endpoint `/health`

**Describe the solution you'd like**
It would be beneficial to have a default /health endpoint integrated into the framework, in addition to the default docs URL. This endpoint could be something like [fastify-healthcheck](https://github.com/smartiniOnGitHub/fastify-healthcheck) and would automatically modify the status to reflect any detected issues.

**Comment by ardatan** [comment]
I think it can be a plugin just like Fastify one you shared. PRs are welcome!
