### ISSUE TITLE
type OASResponseBody is missing

### ISSUE THREAD

**Issue by byudaniel** [ardatan/feTS#257]
The documentation references `type OASResponseBody`, so that you can easily refer to the response body type for a particular path and status code, but it does not exist.

I've started recreating it, but this solution only has a union of all possible responses, regardless of status code:
```typescript
export type ResponseType<
  T extends keyof (typeof oas)['paths'],
  K extends keyof (typeof oas)['paths'][T]
> = Awaited<ReturnType<OASResponse<Mutable<typeof oas>, T, K>['json']>>
```

What is the best way to get the response type for a certain status code? Do you plan on adding OASResponseBody?

**Comment by byudaniel** [comment]
This type would get me what I'm looking for:
```typescript
export type OASResponseBody<TOAS extends OpenAPIDocument, TPath extends keyof TOAS['paths'], TMethod extends keyof TOAS['paths'][TPath], TStatus extends keyof OASStatusMap<TOAS, TPath, TMethod> = keyof OASStatusMap<TOAS, TPath, TMethod>> = Awaited<ReturnType<{
    [K in TStatus]: TypedResponse<FromSchema<FixJSONSchema<OASJSONResponseSchema<TOAS, TPath, TMethod, K>>>, Record<string, string>, K extends StatusCode ? K : K extends 'default' ? NotOkStatusCode : K extends `${number}${number}${number}` ? ToNumber<K> extends StatusCode ? ToNumber<K> : 200 : 200>;
}[TStatus]['json']>>;
```

**Comment by ardatan** [comment]
Thanks for opening the issue :) It should be `OASOutput` instead. We have just updated it!
