### ISSUE TITLE
Feedback for “Utilizing Middlewares”

### ISSUE THREAD

**Issue by generalcss** [ardatan/feTS#340]
Great stuff, but I can't seem to use RouteHandler as a type on a separate handler function., it's expecting multiple types <1,2,3> to be passed.

RouteHandler requires 3 type arguments.

`const authHandler: RouteHandler = (req, ctx) => {
  if (!req.headers.get("Authorization")) {
    return new Response(null, { status: 401 });
  }
};`

**Comment by ardatan** [comment]
Thanks for the feedback!
Fixed in #341 !
