### ISSUE TITLE
Question about async handler

### ISSUE THREAD

**Issue by generalcss** [ardatan/feTS#346]
I'm still trying out feTS on the backend but am stuck at my first db query. I'm trying a mongoose find here, but uWebsockets hangs up as soon as I call 'await User.find()`. It gives me 
'Error: Returning from a request handler without responding or attaching an abort handler is forbidden! libc++abi: terminating'.

I've tested the find method outside the router code, and it works as expected.

`.route({
    description: "Get all users",
    method: "GET",
    path: "/users",
    schemas: { \** **\ },
    handler: async (request) => {
      const users = await User.find();

      return Response.json(users);

     // wrapping in a try catch also did nothing 
      try {
        return Response.json(allUsers);
      } catch (err) {
        console.log(err);
      }

      return Response.json({ message: "ok" });
    },
  })`

**Comment by ardatan** [comment]
Closing the issue for now. We can reopen if it still persists.
