### ISSUE TITLE
Module '"fets"' has no exported member 'useCookies'

### ISSUE THREAD

**Issue by francelwebdev** [ardatan/feTS#405]
**Describe the bug**
Module '"fets"' has no exported member 'useCookies'

**Environment:**
const router = createRouter<FetchEvent>({
	plugins: [
		useCORS({
			origin: '*',
			credentials: true,
			// allowedHeaders: ['X-Custom-Header'],
			// methods: ['POST']
		}),
		useCookies()
	]
})

CLoudflare worker

**Comment by ardatan** [comment]
Thanks for the feedback!
It was a documentation issue! Fixed in https://github.com/ardatan/feTS/commit/db14a3d2c33ee7b5d0b002d34a9334d04b85e1c3
