### ISSUE TITLE
Auto-generated Swagger UI is unstyled

### ISSUE THREAD

**Issue by m-abdelwahab** [ardatan/feTS#436]
**Describe the bug**

The auto-generated Swagger UI is unstyled

<img width="1728" alt="Arc-002903" src="https://github.com/ardatan/feTS/assets/27310414/e0a7b63b-3a35-4db6-ad52-ba338e5fe5ad">

**To Reproduce**  

1. Project setup using a simple Cloudflare Worker

```bash
npm create cloudflare

╭ Create an application with Cloudflare Step 1 of 3
│
├ In which directory do you want to create your application?
│ dir ./fets-cf
│
├ What type of application do you want to create?
│ type "Hello World" Worker
│
├ Do you want to use TypeScript?
│ yes typescript
│
├ Copying files from "hello-world" template
│
├ Do you want to use TypeScript?
│ yes typescript
│
├ Retrieving current workerd compatibility date
│ compatibility date 2023-08-01
│
├ Do you want to use git for version control?
│ yes git
│
╰ Application created

cd fets-cf

npm i fets
```
2. update `workers.ts` to:

```ts
export interface Env {}

import { createRouter, Response } from 'fets';

const router = createRouter({
	openAPI: {
		endpoint: '/openapi.json',
	},
	swaggerUI: {
		endpoint: '/docs',
	},
}).route({
	method: 'GET',
	path: '/greetings',
	schemas: {
		responses: {
			200: {
				type: 'object',
				properties: {
					message: {
						type: 'string',
					},
				},
				required: ['message'],
				additionalProperties: false,
			},
		},
	} as const,
	handler: () => Response.json({ message: 'Hello World!' }),
});

export default {
	fetch: router.fetch,
};
```

3. run `npm start` to start the development server and go to http://127.0.0.1:8787/docs

**Expected behavior**
It should have some styling

**Comment by m-abdelwahab** [comment]
I just saw [this example](https://github.com/ardatan/feTS/blob/master/examples/trpc-openapi/src/pages/swagger.tsx) that uses https://www.npmjs.com/package/swagger-ui-react. It would be really cool if there were built-in styles like the GraphQL playground :)

**Comment by m-abdelwahab** [comment]
Just saw that Styles should be loaded 🤔

https://github.com/ardatan/feTS/blob/ae0882a517f5da110242c4ed1ecc54f46850e1ad/packages/fets/src/swagger-ui.html#L9

**Comment by YassinEldeeb** [comment]
Hey @m-abdelwahab it looks like this CDN is blocked in Egypt, if you use a VPN somewhere else, it'd load the CSS styles.

**Comment by YassinEldeeb** [comment]
@ardatan maybe this CSS styles can be loaded locally from a file instead?

**Comment by m-abdelwahab** [comment]
Looking at the repo: https://github.com/Itz-fork/Fastapi-Swagger-UI-Dark

It can be loaded from GitHub https://raw.githubusercontent.com/Itz-fork/Fastapi-Swagger-UI-Dark/main/assets/swagger_ui_dark.min.css

**Comment by ardatan** [comment]
Cool! Would you create a PR for this change?

**Comment by m-abdelwahab** [comment]
With pleasure!

**Comment by ardatan** [comment]
Thank you @m-abdelwahab 🙏

**Comment by YassinEldeeb** [comment]
> @YassinEldeeb It'd increase the bundle size :/

ah, right :(

thank you @m-abdelwahab for the solution and PR!!

**Comment by ardatan** [comment]
Thank you for the feedback and the PR @m-abdelwahab ! We can close it now, right?
