### ISSUE TITLE
Param Type is coming through as `never` when it should be `number`

### ISSUE THREAD

**Issue by frednomoon** [ardatan/feTS#470]
**Describe the bug**

The Schema below describes an endpoint which takes an `id` param. This client should presumably figure out the type for this param as defined in the schema but it is outputting the type `never`. This makes the client unusable. Not sure if there is an issue in the schema or if something is going wrong?

**To Reproduce** Steps to reproduce the behavior:

Using the following schema file:

```
export default {
  openapi: "3.0.0",
  info: {
    title: "test",
    version: "0.1.0",
  },
  paths: {
    "/{id}/meters": {
      get: {
        parameters: [
          {
            name: "id",
            in: "path",
            required: true,
            schema: {
              type: "integer",
              format: "int64",
            },
          },
        ],
        responses: {
          "200": {
            description: "",
            content: {
              "application/json": {
                schema: {
                  type: "array",
                  items: {
                    $ref: "#/components/schemas/Something",
                  },
                },
              },
            },
          },
          default: {
            description: "",
          },
        },
        security: [
          {
            Authorization: [],
          },
        ],
      },
    },
    securitySchemes: {
      Authorization: {
        description: "Requires JWT to access",
        type: "http",
        scheme: "bearer",
        bearerFormat: "bearer",
      },
    },
  },
} as const;
```

then using the generator as follows i get the TS error

```
import { createClient, type NormalizeOAS } from "fets";
import type openapi from "./openapi";

const client = createClient<NormalizeOAS<typeof openapi>>({});

const response = await client["/{id}/meters"].get({
  params: {
    id: 123,
  },
  headers: {
    Authorization: `Bearer ${123}`,
  },
});
```

**Comment by ardatan** [comment]
Could you test this again with `fets@0.4.11`?

**Comment by ardatan** [comment]
Closing the issue for now. Let's know if the issue persists.

**Comment by spookyuser** [comment]
I have a similar issue i think where, there's just not type hints from vscode on any of the endpoints, idk if there are supposed to be but i don't get any

**Comment by spookyuser** [comment]
I had a similar issue, i actually thought there were no types at all but i left out a trailing / and then all the types came through, thanks sm i love this library!

**Comment by ardatan** [comment]
@spookyuser Could you help us reproducing it?

**Comment by spookyuser** [comment]
Sure! So in this example it would be like `await client["/{id}/meters"]` where without the slash after meters vscode doesn't seem to be able to infer any types and so you don't get feedback about params, or the body and the response is undefined but  vs `await client["/{id}/meters/"]` where suddenly everything comes through. I'm 99% sure that was the only thing i changed.

**Comment by ardatan** [comment]
The example in the main post is missing "Something" component. Maybe that's the issue. Would you create an issue with a reproduction? Thanks!

**Comment by spookyuser** [comment]
Sure if it happens again i will!
