### ISSUE TITLE
Generated Swagger UI is unstyled

### ISSUE THREAD

**Issue by roertbb** [ardatan/feTS#626]
**Describe the bug**

Generated Swagger UI is unstyled

<img width="1432" alt="fets" src="https://github.com/ardatan/feTS/assets/20808724/4d671940-05a0-4c06-a5ad-6ad3670677bc">

**To Reproduce** Steps to reproduce the behavior:

https://codesandbox.io/p/sandbox/ecstatic-shirley-fnhm59?file=%2Fapp%2Fpage.tsx%3A6%2C1

**Expected behavior**

Swagger UI should be properly styled

**Environment:**

- see CodeSandbox link
- dark mode

**Additional context**

It seems that the dark-mode is not working properly. It's caused most likely by dark mode styles [(https://raw.githubusercontent.com/Itz-fork/Fastapi-Swagger-UI-Dark/main/assets/swagger_ui_dark.min.css)](https://raw.githubusercontent.com/Itz-fork/Fastapi-Swagger-UI-Dark/main/assets/swagger_ui_dark.min.css) to be returned with `Content-Type: text/plain` instead of `Content-Type: text/css`

**Comment by ardatan** [comment]
Fixed in the latest version!
