### ISSUE TITLE
`zod`: provide openapi metadata

### ISSUE THREAD

**Issue by n1ru4l** [ardatan/feTS#677]
**Is your feature request related to a problem? Please describe.**

We need some way to name types, give examples, etc.

```ts

const UserModel = z.object({
  id: z.string().uuid().openapi({ example: 'some-uuid' })
}).openapi({
  "name": "User",
})
```

https://github.com/asteasolutions/zod-to-openapi/blob/master/src/zod-extensions.ts

**Describe the solution you'd like**

Zod to openapi does some voodoo magic for embedding metadata: https://github.com/asteasolutions/zod-to-openapi
We might do something similar.

**Comment by ardatan** [comment]
We dropped Zod in favor of TypeBox
