### ISSUE TITLE
Missing POST json body not considered a TS error

### ISSUE THREAD

**Issue by dodas** [ardatan/feTS#799]
Consider following route:
```ts
const router = createRouter().route({
  method: "POST",
  path: "/hello",
  handler: () => Response.json("hi"),
  schemas: {
    request: {
      json: Type.Object({
        name: Type.String(),
      }),
    },
  },
});
```

Calling this route without `json` raises no error about missing json with `name` property:
```ts
client["/hello"].post(); // < No error
```

However, when `json` property is present, but `name` is missing, error is correctly raised:

```ts
client["/hello"].post({
  json: {}, // < Property 'name' is missing in type '{}' but required in type '{ name: string; }'.ts(2741)
});
```

**Comment by m4rvr** [comment]
This seems like a similar issue here, but with the params instead https://github.com/ardatan/feTS/discussions/896
