### ISSUE TITLE
It always complains to add authorization token

### ISSUE THREAD

**Issue by beerose** [ardatan/feTS#857]
### Discussed in https://github.com/ardatan/feTS/discussions/399

<div type='discussions-op-text'>

<sup>Originally posted by **sankaSanjeeva** July 27, 2023</sup>
I have added an Authorization token using a plugin but it gives me type error requesting headers again. Is there any way to configure it?

![Screenshot 2023-07-27 at 19 20 58](https://github.com/ardatan/feTS/assets/44424604/f391a071-21e2-4c19-af5c-a59e75d3e81e)
</div>

**Comment by thelinuxlich** [comment]
Thanks @beerose

**Comment by ericwilhite** [comment]
Spun up a new project today and immediately ran into this. Glad to see it's already a PR!
