### ISSUE TITLE
Next.js app router "no response returned"

### ISSUE THREAD

**Issue by sarimabbas** [ardatan/feTS#927]
**Describe the bug**

Hello! Thanks so much for your work on feTS, it looks great and I am excited to try it

The issue I am facing is that when navigating to a feTS route using Nextjs app router, I get "Not found error": 

```
⨯ Error: No response is returned from route handler '.../apps/my-api/app/v1/[...slug]/route.ts'. Ensure you return a `Response` or a `NextResponse` in all branches of your handler.
    at .../node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63416
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I am using `pnpm`, `turborepo`, `fets ^0.6.8` and `next 14.0.4`. 

**To Reproduce** Steps to reproduce the behavior:

I created a minimal example to reproduce the bug: https://github.com/sarimabbas/fets-reproduction 

**Expected behavior**

I expect to navigate to `http://localhost:3000/v1` and see "Hello world" instead I get a 404. 

**Environment:**

- OS: macos sonoma 14.0 
- `package-name...`: fets ^0.6.8 
- NodeJS: v21.4.0

**Additional context**

for context, i am trying to deploy an restful api using nextjs + feTS. I want to version my api like `v1`, `v2` etc and use multiple feTS routers. I am using a catchall route like the example you have here https://github.com/ardatan/feTS/blob/master/examples/nextjs-app-dir/src/app/api/%5B...slug%5D/route.ts 

thanks so much for your help!

**Comment by ardatan** [comment]
Thanks for creating the issue but I cannot access the repo you shared. Also it would be easier for us if you use something like CodeSandbox for the reproduction.

**Comment by sarimabbas** [comment]
I'm so sorry, I made the repository public, so it should be accessible now.

I'll also make a CodeSandbox and post it here shortly

**Comment by sarimabbas** [comment]
So sorry for the delay, here is the [CodeSandbox reproduction](https://codesandbox.io/p/github/sarimabbas/fets-reproduction/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqk8ez2d00063b6faqlixwba%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqk8ez2d00023b6f86ej6wcj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqk8ez2d00043b6fhltvzqjb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqk8ez2d00053b6fljhm5o8i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqk8ez2d00023b6f86ej6wcj%2522%253A%257B%2522id%2522%253A%2522clqk8ez2d00023b6f86ej6wcj%2522%252C%2522activeTabId%2522%253A%2522clqk8p34v00r83b6fr36srq5o%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqk8ez2d00013b6fhu9luyx4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clqk8p34v00r83b6fr36srq5o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clqk8ez2d00053b6fljhm5o8i%2522%253A%257B%2522id%2522%253A%2522clqk8ez2d00053b6fljhm5o8i%2522%252C%2522activeTabId%2522%253A%2522clqk8r6op00h13b6fr7vnkwyu%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqk8r6op00h13b6fr7vnkwyu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clqk8ez2d00043b6fhltvzqjb%2522%253A%257B%2522id%2522%253A%2522clqk8ez2d00043b6fhltvzqjb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqk8ez2d00033b6fz62j19ak%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqk8ezkm000eefhs15hx4ttc%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqk8f15300573b6frqklzwyh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clqk8fd1o008q3b6f28kzlvzo%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqk8f15300573b6frqklzwyh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A27.411705348133196%257D). Please let me know if you are able to access it. Thanks so much again for your help!

**Comment by ardatan** [comment]
Fixed in the underlying library;
https://github.com/ardatan/whatwg-node/releases/tag/release-1704197580723
It should be fixed after updating the lock file.
